name: output test
on: 
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      my_output: ${{ steps.step1.outputs.test_val }}
    steps:
      - id: step1
        run: echo "test_val=hello-world" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "The value from job1 was ${{ needs.job1.outputs.my_output }}"
