name: first demo workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-24.04
    steps:
      - name: first demo
        run: |
          echo "first demo workflow to run multiple shell commands once"
          echo "done!" 
